// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "verticalTabs.enabled": boolean;
      "verticalTabs.collapsed": boolean;
      "verticalTabs.pinned": boolean;
      "verticalTabs.categoryColors": string;
      "verticalTabs.rememberCategories": boolean;
      "verticalTabs.showExtra": boolean;
      "verticalTabs.autoCloseEnabled": boolean;
      "verticalTabs.autoCloseDays": number;
      "verticalTabs.disableBlur": boolean;
      "verticalTabs.tabHeight": string;
    };
  }
}
