// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "verticalTabs.enabled": boolean;
      "verticalTabs.collapsed": boolean;
      "verticalTabs.pinned": boolean;
      "verticalTabs.categoryColors": string;
      "verticalTabs.showExtra": boolean;
      "verticalTabs.showReaderLoadedIndicator": boolean;
      "verticalTabs.autoCloseEnabled": boolean;
      "verticalTabs.autoCloseDays": number;
      "verticalTabs.protectCategorizedTabs": boolean;
      "verticalTabs.releaseReaderEnabled": boolean;
      "verticalTabs.releaseReaderMinutes": number;
      "verticalTabs.tabHeight": string;
      "verticalTabs.enableBlur": boolean;
      "verticalTabs.nativeTabBarHidden": boolean;
      "verticalTabs.autoExpand": boolean;
      "verticalTabs.autoExpandEmbedded": boolean;
      "verticalTabs.applyExpandCollapseAnimation": boolean;
      "verticalTabs.compactStrip": boolean;
    };
  }
}
